repos:
  - repo: local
    hooks:
      - id: clean-notebooks
        name: clean notebooks
        entry: python scripts/clean_notebooks.py notebooks
        language: system
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
